name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure git identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"

      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://<Jamekorn>:$HF_TOKEN@huggingface.co/spaces/<Jamekorn>/<Deployment-Tut>
          git push --force space HEAD:main
